// lib/gallery.ts

export const CATEGORIES = [
  "All",
  "Custom Homes",
  "Kitchens",
  "Bathrooms",
  "Millwork",
  "Cabinetry",
  "Remodels",
  "Woodwork",
] as const;

export const GALLERY = [
  {
    id: 1,
    title: "Modern Luxury Kitchen",
    category: "Kitchens",
    image: "https://picsum.photos/id/1018/900/1200",
    location: "Houston, TX",
    year: "2025",
  },
  {
    id: 2,
    title: "Elegant Bathroom",
    category: "Bathrooms",
    image: "https://picsum.photos/id/1015/900/1200",
    location: "Dallas, TX",
    year: "2025",
  },
  {
    id: 3,
    title: "Custom Millwork",
    category: "Millwork",
    image: "https://picsum.photos/id/1025/900/1200",
    location: "Austin, TX",
    year: "2024",
  },
  {
    id: 4,
    title: "Luxury Cabinetry",
    category: "Cabinetry",
    image: "https://picsum.photos/id/1035/900/1200",
    location: "Houston, TX",
    year: "2024",
  },
  {
    id: 5,
    title: "Luxury Remodel",
    category: "Remodels",
    image: "https://picsum.photos/id/1043/900/1200",
    location: "San Antonio, TX",
    year: "2025",
  },
  {
    id: 6,
    title: "Custom Home Exterior",
    category: "Custom Homes",
    image: "https://picsum.photos/id/1050/900/1200",
    location: "Houston, TX",
    year: "2023",
  },
  {
    id: 7,
    title: "Designer Woodwork",
    category: "Woodwork",
    image: "https://picsum.photos/id/1060/900/1200",
    location: "Dallas, TX",
    year: "2025",
  },
  {
    id: 8,
    title: "Luxury Living Room",
    category: "Custom Homes",
    image: "https://picsum.photos/id/1074/900/1200",
    location: "Austin, TX",
    year: "2025",
  },
  {
    id: 9,
    title: "Premium Kitchen Island",
    category: "Kitchens",
    image: "https://picsum.photos/id/1084/900/1200",
    location: "Houston, TX",
    year: "2024",
  },
  {
    id: 10,
    title: "Master Bathroom Suite",
    category: "Bathrooms",
    image: "https://picsum.photos/id/1080/900/1200",
    location: "Dallas, TX",
    year: "2023",
  },
];